### ISSUE TITLE
libraries installed, backends not visible

### ISSUE THREAD

**Issue by macromeer** [AstraZeneca/napari-wsi#8]
Hi there,

thanks for this plugin. I have installed the openslide library (using it in another conda env, too), but the backend is not visible in the widget.

`pip install openslide-python openslide-bin`

napari: 0.4.19.post1
Python: 3.9.21 | packaged by conda-forge | (main, Dec 5 2024, 13:51:40) [GCC 13.3.0]
Qt: 5.15.14
PyQt5: 5.15.11
NumPy: 1.24.4
SciPy: 1.9.1
Dask: 2024.8.0
VisPy: 0.14.3
magicgui: 0.10.0
superqt: 0.7.1
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
- GL version: 4.5 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1804x1096, scale 1.0

**Comment by pmplewa** [comment]
There was a delay in publishing the latest version of the plugin, which adds the openslide backend, to conda-forge, but it should be available now.

Here is an example conda environment file that sets up the updated plugin as well as openslide:

```yaml
name: napari-wsi
channels:
  - conda-forge
dependencies:
  - napari
  - napari-wsi=1.*
  - openslide=4.0.*
  - openslide-python=1.4.*
  - pyqt
  - python=3.11
```

In particular, this also installs python 3.11, which is now the minimum required version. You can create a new conda environment based on this file (`napari-wsi.yml`) with:

```bash
conda env create -f napari-wsi.yml
```

Then activate the environment and start napari with:

```bash
conda activate napari-wsi
napari
```

This should allow you to read images using the openslide backend. I hope this helps!
